### PR TITLE
Complete User Service with Register (Create new user), Login, Logout, Update and Get user by ID Endpoints

### PR DESCRIPTION
**Pull request by Lilemanalu**

### CODE REVIEW

**Comment by install18** [comment]
Why not create a new table for the user's token for authentication?

**Comment by install18** [comment]
For BCrypt, why not just use a library?

**Comment by install18** [comment]
Why validate the request in service instead of controller

**Comment by Lilemanalu** [comment]
> Why not create a new table for the user's token for authentication?

Actually, it was done for simplicity. Since I implemented the authentication within the user service, I chose to store the token and expiration date in the same table with the user data.
However, in the future, I plan to separate the authentication from the user service. I'll create a table for storing tokens and their expiration dates, and the authentication service will operate independently from the user service.

**Comment by Lilemanalu** [comment]
> For BCrypt, why not just use a library?

I just recently started learning about authentication, and BCrypt was the only thing I knew how to use. For now, I went with BCrypt because it was what I was familiar with.
In future projects, I’ll definitely look into using libraries for authentication to make things even better.

**Pull request merged**
